project:
  type: book
  output-dir: docs

execute:
   echo: false
   warning: false

book:
  title: "Manual de Uso"
  author: "Dirección de Investigación y Publicaciones"
  date: "last-modified"
  chapters:
    - index.qmd

    
# bibliography: ocs.bib

format:
  html:
    theme: cosmo
  # pdf:
  #   documentclass: scrreprt