project:
  type: book
  output-dir: docs

execute:
   echo: false
   warning: false

book:
  title: "Ciencia de Datos en Investigación -- CINDAI"
  subtitle: "Manual de Uso"
  author: "Dirección de Investigación y Publicaciones"
  repo-url: https://github.com/facso-investigacion
  site-url: https://facso.uchile.cl/facultad/direcciones-y-coordinaciones/direccion-de-investigacion-y-publicaciones
  sidebar:
   logo: input/images/logo-DIP-25.png
  date: "last-modified"
  chapters:
    - index.qmd
    - repositorio.qmd
    - base-integrada.qmd
    - consultas.qmd
    - datos-abiertos.qmd
    - actualizacion.qmd

    
# bibliography: ocs.bib

format:
  html:
    theme: journal
    mermaid: 
      theme: neutral

lang: es

  # pdf:
  #   documentclass: scrreprt