## Metadatos {#sec-metadata} 

Se llevará un registro de los metadatos de las bases de datos en formato `.yml`. A continuación, se muestra un ejemplo básico de metadata contenida en los repositorios

``` yaml
title: "Datos de Investigación de la Facultad de Ciencias Sociales"
creator: "Dirección de Investigación y Publicaciones, Facultad de Ciencias Sociales, Universidad de Chile"
date: "2025"
identifier: "TBD"
url: "https://github.com/facso-investigacion/bases-datos-dip"
description: >
  Esta propuesta tiene como objetivo desarrollar un sistema local e integrado de gestión y visualización de información científica
  en la Facultad de Ciencias Sociales. Este sistema permitirá consolidar, actualizar y utilizar estratégicamente los datos de los
  proyectos de investigación, garantizando que sean encontrables, accesibles, interoperables y reutilizables. Con ello, se busca 
  mejorar la transparencia, eficiencia y sostenibilidad en la gestión de la información científica de la Facultad.
subject: "Gestión de Información Científica"
format: 
 - ".csv"
 - ".rdata"
license: "TBD"
language: "es"
relationship:
  - type: "isPartOf"
    id: "https://github.com/facso-investigacion"
    description: "Parte de la Organización de la Dirección de Investigación en Github"
source: "Los datos fueron recopilados a partir de datos de SEPA-VID, ANID y FACSO"
contact:
  name: "Dirección de Investigación FACSO"
  email: "asistenteinvestigacion@facso.cl"
  phone: "+56 2 2978 9728"

# Historial de versiones -- Cambiar antes de cada commit.

versions: 
 - id: "0.1.0"
   last_updated: "2025-08-04"
   updated_by: "Gabriel Cortés"
   update_note: "Crea documento YAML para el almacenamiento interoperable de metadatos"
 - id: "0.2.0"
   last_updated: "2025-08-05"
   updated_by: "Gabriel Cortés"
   update_note: "Agrega postulaciones a proyectos FONDECYT 2026 de IR-FACSO"
```

Parte importante del registro de metadatos es que permite llevar un seguimiento exhaustivo, accesible e interoperable del historial de versiones de las bases de datos y repositorios. Se propone que se debe registrar, antes de cada commit, los siguientes campos:

1.  `id` Número de versión siguiendo el estándar del Versionamiento Semántico introducido en el @sec-consultas
2. `last_updated`: fecha de modificación
3.  `updated_by`: Autor de la modificación.
4.  `update_note`: Comentario explicativo de los cambios.

## Actualización

1. Asegurarse de haber realizado un commit

2. Exportar historial de commit con el siguiente código en la terminal. 

``` bash
git log --pretty=format:"%ad | %s%d | %an" --date=short > input/data/procesadas/commits.txt
```

-  Esto genera un archivo `.txt`que es procesado en `proc/proc-metadata.R`. Esto genera el archivo `_metadata.yml`
