# App de Consultas Internas {#sec-consultas}

Para facilitar la consulta y la generación de reportes sobre datos de investigación de la Facultad, CINDAI pone a disposición una app interna para realizar consultas de manera rápida y eficiente. La app está disponible en este [enlace](https://dip-facso.shinyapps.io/consultas/#consulta-proyectos).

## Repositorio, Construcción y Publicación

La app se encuentra en el repositorio `bases-datos-dip/app`, el cual tiene la siguiente estructura. 

```plaintext
├── data/
│   ├── data-general.rdata
|   ├── data-proyectos.rdata
├── consultas.qmd
├── consultas.html
├── consultas_files/
├── deploy.R
├── www/
│   ├── codebook.qmd
│   ├── codebook.html
```

Como se comentó en el @sec-base, el archivo `data-general.rdata` corresponde a la Base Integrada de Datos en Investigación, creada, actualizada e importada automáticamente al ejecutar el `masterscript` del repositorio. Esta es una base *long* que tiene como unidad de análisis académicos-proyectos. 

`data-proyectos.rdata` se crea a partir de la Base Integrada con el script `base-wide.R`, como se detalla en @sec-base. Esta es una base *wide* que tiene como unidad de análisis los proyectos de investigación. 

El archivo `consultas.qmd` contiene el código que crea la app. Ésta fue construida en [R Shiny](https://shiny.posit.co/r/getstarted/shiny-basics/lesson1/), un paquete de R que permite la construcción de aplicaciones web directamente con lenguaje R, y que se encuentra [integrado con Quarto](https://quarto.org/docs/interactive/shiny/). Al renderizar este documento se crea el archivo `consultas.html` y la carpeta `consultas_files/`, que permiten previsualizar la app.

En la carpeta `www/` se puede encontrar el archivo `codebook.qmd`, que crea un libro de códigos para las variables de la aplicación. 

El archivo `deploy.R` permite la publicación de la app en la web. La app se encuentra alojada en los servidores de [shinyapps](https://www.shinyapps.io/). 

## Uso

### Pestaña de Académicos

En esta pestaña podrá ver los proyectos de investigación vinculados a cada académico de la Facultad, ya sea como Investigador Responsable o Coinvestigador. Para hacerlo, debe seguir los siguientes pasos:

1) Seleccionar a un académico o académica en la parte superior izquierda de la aplicación.

2) Seleccionar los filtros deseados. Actualmente los filtros disponibles son: Año(s) del Concurso; Proyectos en que el académico participó como Investigador Responsable; Proyectos adjudicados; Proyectos en ejecución; proyectos asociativos; proyectos de investigación aplicada; institución, concurso e instrumento del proyecto; jerarquía del académico al adjudicarse el proyecto.

3) Una vez realizados los pasos anteriores, se generará una tabla en la sección derecha de la aplicación. Esta tabla es exportable en formato excel o csv, según estime conveniente.

### Pestaña de Proyectos

En esta pestaña podrá acceder a la totalidad de los proyectos de investigación adjudicados por académicos de la Facultad, incluyendo información sobre investigadores responsables, coinvestigadores, financiamiento, etc. Para hacerlo debe seguir los siguientes pasos.

Para ello debe seleccionar los filtros deseados. De no seleccionar ninguno, se generará una tabla con la totalidad de los proyectos disponibles. Al igual que en la pestaña de académicos, esta tabla es exportable en formato excel y csv.

### Libro de Códigos

Puede consultar el libro de códigos de ambas pestañas [aquí](https://dip-facso.shinyapps.io/consultas/_w_13f4a94ea5194a07abbd823f4c5537d2/www/codebook.html)


### Reporte de Problemas y Sugerencias

Para reportar algún problema, error en la información, o hacer sugerencias sobre funcionalidades de la app, existen dos alternativas:

1) Abrir un [issue](https://github.com/facso-investigacion/bases-datos-dip/issues) en el repositorio de Github de la aplicación. Para hacerlo, necesita una cuenta en Github y acceso al repositorio.

2) Por correo electrónico a [asistenteinvestigacion@facso.cl](mailto:asistenteinvestigacion@facso.cl)

## Versionamiento

Se llevará a cabo un control de versiones con [Versionamiento Semántico 2.0.0](https://semver.org/lang/es/). El versionamiento semántico sigue un estándar MAJOR.MENOR.PARCHE (o X.Y.Z), donde:

- MAJOR representa cambios en la compatibilidad entre versiones
- MINOR representa cambios en funcionalidades compatibles con versiones anteriores
- PARCHE representa correccione en errores compatibles con las versiones anteriores.

Este versionamiento se puede hacer en el repositorio alojado en Github, con las funcionalidades `tags`y `release`. O bien, directamente en la terminal con el siguiente código.

```bash
git tag -a vx.y.z -m "Versión x.y.z: titulo"
```

## Licencia

Las aplicación y su contenido está protegida bajo la [Licencia Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0). Apache 2.0 es una licencia de software libre y de código abierto que permite el uso, modificación y distribución del código con fines tanto comerciales como no comerciales, siempre que se mantenga la atribución al autor original y se conserve una copia del texto de la licencia. 