# Introducción

Frente a la necesidad de contar con datos gobernados y actualizados sobre las actividades de investigación de la Facultad de Ciencias Sociales, que permitan trazar y analizar las trayectorias académicas y fortalecer la generación de reportes integrados sobre productividad científica, la Dirección de Investigación y Publicaciones (DIP) propone la creación **CINDAI**. Con CINDAI, buscamos desarrollar un sistema local e integrado de gestión, producción y visualización de información científica en la Facultad de Ciencias Sociales. Este sistema integrará, consolidará y mantenderá actualizados los datos relacionados con las postulaciones a proyectos de investigación de los académicos/as de la Facultad, transformándolos en información confiable y oportuna para la comunicación y la toma decisiones. 

La propuesta se basa en la aplicación de los **principios FAIR** (*Findable, Accesible, Interoperable and Reusable*). Estos principios buscan crear un ecosistema de gestión del conocimiento más abierto y eficiente, facilitando que los datos sean fácilmente localizable, accesibles, integrables y reutilizables tanto por personas como por sistemas [(Hartley Belmar et al., 2025)](https://zenodo.org/records/15856492).

La implementación de estos principios en la gestión de información no solo mejora el acceso y uso eficiente de los datos, sino que también impulsa una cultura institucional de apertura, colaboración y transparencia en la investigación. Al incorporar los principios FAIR en la estructura y gobernanza de datos de la Facultad, CINDAI busca transformar la manera en que se gestionan, actualizan y reutilizan los datos, garantizando su accesibilidad, reproducibilidad y valor público para la comunidad académica.

En coherencia con estos principios, y con el propósito de asegurar la reusabilidad y correcta operación del sistema, se pone a disposición del equipo de la DIP este Manual de Uso de CINDAI. Su objetivo es presentar las principales características de la plataforma, explicar su arquitectura y flujos de trabajo, y detallar los procedimientos necesarios para mantener actualizada la información y asegurar su calidad.

A continucación, en el @sec-repo, se presentará los repositorios y el entorno de trabajo que aloja CINDAI. Luego, en el @sec-base, se explica la estructura, construcción y flujo de trabajo del principal producto de CINDAI -- La Base Integrada de Datos de Investigación. En el @sec-consultas, se explica la construcción y las condiciones de uso de la [App de Consultas Internas de CINDAI](https://dip-facso.shinyapps.io/consultas/). En el @sec-abiertos, se presenta el proceso de anonimización de la Base Integrada, lo que permite la creación de Datos Abiertos CINDAI. Enel @sec-visualizador, se explica la construcción del [Visualizador de Datos Abiertos de CINDAI](https://dip-facso.shinyapps.io/datos-abiertos-CINDAI/#inicio), una herramienta interactiva que permita visualizada de manera rápida datos generales, históricos y actuales de las investigaciones de la Facultad. Por último, en el @sec-metadata, se introduce el flujo de trabajo para actualizar los metadatos de CINDAI.