## Repositorios de la Dirección de Investigación y Publicaciones {#sec-repo}

Los repositorios vinculados a la gestión de datos DIP se encuentran alojados en la [Organización de la Dirección en Github](https://github.com/facso-investigacion). En concreto, CINDAI se compone de 5 repositorios:

[**1. CINDAI**](https://github.com/facso-investigacion/CINDAI) <i class="bi bi-link-45deg"></i>

Este repositorio está destinado al público externo y tiene como propósito dar a conocer de manera general el diagnóstico, los objetivos y productos de CINDAI. Esta información se puede encontrar en el siguiente [Documento de Trabajo](https://facso-investigacion.github.io/CINDAI/index.html).

[**2. bases-datos-dip**](https://github.com/facso-investigacion/bases-datos-dip) <i class="bi bi-link-45deg"></i>

Este es un repositorio privado que contiene el procesamiento de las bases originales de SEPA-VID, ANID, personal FACSO entre otras.

En la carpeta `output`se encuentran las bases de datos procesadas en en formato `.rdata` y `.csv`. Estas bases no se encuentran anonimizadas, ya que contienen el rut de los investigadores. Por ello, este repositorio es **exclusivamente para uso interno de equipo DIP**

[**3. datos-abiertos-dip**](https://github.com/facso-investigacion/datos-abiertos-dip) <i class="bi bi-link-45deg"></i>

Este repositorio contendrá las bases anonimizadas en formato `.rdata` y `.csv`. El repositorio será público. Sin embargo, la branch principal se encontrará protegida, de modo que cualquier modificación se pueda realizar solo tras el visto bueno del Equipo DIP.

[**4. visualizador-cindai**](https://github.com/facso-investigacion/visualizador-cindai) <i class="bi bi-link-45deg"></i>

Este repositorio contiene el código del [Visualizador de Datos Abiertos de CINDAI](https://dip-facso.shinyapps.io/datos-abiertos-CINDAI/#inicio).

[**5. documentacion-cindai**](https://github.com/facso-investigacion/documentacion-cindai) <i class="bi bi-link-45deg"></i>

Este repositorio contendrá documentación para el uso correcto de los datos de la Dirección de Investigación, incluyendo libros de códigos y este manual de uso.
