# Visualizador Datos Abiertos {#sec-visualizador}

El Visualizador de Datos Abiertos de CINDAI tiene el propósito de poner a disposición de la comunidad una herramienta interactiva que permita visualizar de manera rápida datos generales, históricos y actuales, de las investigaciones llevadas a cabo en la Facultad. El visualizador se puede encontrar en el siguiente [enlace](https://dip-facso.shinyapps.io/datos-abiertos-CINDAI/#inicio).

## Repositorio, Construcción y Publicación

La app se encuentra en el repositorio `bases-datos-dip/app`, el cual tiene la siguiente estructura. 

```plaintext
├── input/
│   ├── data-general-anon.rdata
|   ├── data-proyectos-anon.rdata
├── visualizador.qmd
├── visualizador.html
├── visualizador_files/
```

`data-general-anon.rdata` y `data-proyectos-anon.rdata` corresponden a las versiones anonimizadas de la Base Integrada y la Base de Proyectos, respectivamente. `visualizador.qmd` es el código que crea la aplicación en `visualizador.html`. Al igual que la App de Consultas, el Visualizador está construido con Shiny y alojado en ShinyApps.

## Uso

[En construcción]

## Versionamiento

Al igual que la App de Consultas, se utiliza versionamiento semántico, descrito en @sec-consultas. 

## Licencia

Las aplicación y su contenido está protegida bajo la [Licencia Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0). Apache 2.0 es una licencia de software libre y de código abierto que permite el uso, modificación y distribución del código con fines tanto comerciales como no comerciales, siempre que se mantenga la atribución al autor original y se conserve una copia del texto de la licencia. 